// src/pages/App.vue
<script setup lang="ts">
import { ref, reactive } from 'vue';
let envValue = ref(process.env.NODE_ENV);
//console.log("page.App.env=", process.env.NODE_ENV)
console.log("envValue=", envValue.value)
</script>

<template>
  <html>
    <head>
        <title>welcome</title>
        <span v-if="envValue === 'develop'"><link href="/static/main.css" rel="stylesheet" />
        </span>
        <span v-else><link href="/public/static/main.css" rel="stylesheet" />
        </span>
    </head>
    <body>
        <div id="app"></div>
        <span v-if="envValue === 'develop'"> <script type="module" src="/static/Home.js"></script>
        </span>
        <span v-else><script type="module" src="/public/static/Home.js"></script>
        </span>
    </body>
  </html>
</template>

<style scoped>
</style>
<!--
-->

// src/pages/App.tsx
import * as React from 'react';

//
export default function Page() { 
    return (
    <html>
        <head>
            <title>welcome</title>
            {(process.env.NODE_ENV === "develop") ? (
                <link href="/static/main.css" rel="stylesheet" /> 
            ): (
                <link href="/public/static/main.css" rel="stylesheet" /> 
            )} 
        </head>
        <div id="app"></div>
        <a href="/">[ home ]</a>
        <a href="/about">[ about ]</a>
        <hr />
        <h1>hello</h1>
    </html>
    );
}
/*
<script type="module" src="/public/static/main.js"></script>
*/
